version: "3.1"
services:
  postgres:
    container_name: mbti-db
    image: postgres:12.8
    environment:
      POSTGRES_DB: "mbti_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./db_build:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - my_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "nikita.shatskiy@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"
    networks:
      - my_network
    depends_on: 
      - postgres
networks:
  my_network: 
    driver: bridge
    
  